name: Deploy playground
on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install deps
        run: |
          bun --version
          bun install --frozen-lockfile
      - name: Build
        run: |
          bun run pre-build
          bun run --bun --filter=@contember/playground build
        env:
          VITE_CONTEMBER_ADMIN_PROJECT_NAME: playground
          VITE_CONTEMBER_ADMIN_SESSION_TOKEN: ${{ secrets.PLAYGROUND_SESSION_TOKEN }}

      - name: Deploy
        run: |
          bun run contember deploy ${{ secrets.PLAYGROUND_DSN }} --root --yes
