name: Deploy playground
on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: '20'

      - name: Install yarn deps
        run: |
          yarn --version
          yarn install --immutable
      - name: Build
        run: |
          yarn pre-build
          yarn workspace @contember/playground build
        env:
          VITE_CONTEMBER_ADMIN_PROJECT_NAME: playground2
          VITE_CONTEMBER_ADMIN_SESSION_TOKEN: ${{ secrets.PLAYGROUND_SESSION_TOKEN }}

      - name: Deploy
        run: |
          yarn run contember deploy ${{ secrets.PLAYGROUND_DSN }} --root --yes
